### ISSUE TITLE
Generate mp4 files

### ISSUE THREAD

**Issue by jvcasillas** [jvcasillas/many_babies_stim#7]
@MZaharieva when you get a chance could you create mp4 files for:

- `circle_high_complexity_movement_c8.gif`
- `circle_low_complexity_movement_c8.gif`

**Comment by Vantoine2019** [comment]
@jvcasillas It seems that the background color of the current files are not the right one. I reused your scripts and it gave me correct files!

@MZaharieva I would finally need the .mp4 for the two files mentioned above but with the correct bg color:
    circle_high_complexity_movement_c8.gif
    circle_low_complexity_movement_c8.gif

You can find them here : https://github.com/Vantoine2019/mbah-vp/tree/main/stim

(Joseph I didn't want to spam you with pull requests since I'm testing several possible configurations!)

**Comment by jvcasillas** [comment]
Thanks @Vantoine2019 !

**Comment by jvcasillas** [comment]
@MZaharieva I'm wondering if this is just something I can do myself. Possibly with an online converter? Is there anything critical that I need to know/do to ensure that the output file duration is 1 second?
